<?php

namespace greebo\essence;

require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__) . '/../../../../../src/greebo/essence/Controller.php';
require_once dirname(__FILE__) . '/../../../../../src/greebo/essence/HttpController.php';
require_once dirname(__FILE__) . '/../../../../../src/greebo/essence/HttpRequest.php';
require_once dirname(__FILE__) . '/../../../../../src/greebo/essence/HttpException.php';

/**
 * Test class for Controller.
 * Generated by PHPUnit on 2010-04-08 at 12:25:51.
 */
class HttpControllerTest extends \PHPUnit_Framework_TestCase
{
    /** @var Controller */
    protected $controller;

    protected function setUp()
    {
        $this->controller = new HttpController;
    }

    /**
     * @expectedException greebo\essence\HttpException
     */
    public function testEmptyRequest()
    {
        $request = new HttpRequest(array(), array(), array(), array(), array());
        $this->controller->handle($request);
    }

    /**
     * @expectedException greebo\essence\HttpException
     */
    public function testNoAction()
    {
        $request = new HttpRequest(array(), array(), array(), array(), array());
        $request->action = 'foo';
        $this->controller->handle($request);
    }
}
